### ISSUE TITLE
What do you think about SharedDB?

### ISSUE THREAD

**Issue by Kroid** [dmonad/crdt-benchmarks#1]
SharedDB is not CRDT, it is OT, but it's used for the same purpose. Maybe we should add it to the benchmarks?

**Comment by dmonad** [comment]
I think that would be great! 
Although we would need to make sure that it fairly compares ShareDB with Yjs&Automerge. For the concurrency tests it is necessary to maintain a central ShareDB server. While the CRDTs don't need that. 

I'm not that familiar with ShareDB, but if you would be willing to research how to setup ShareDB in this benchmark environment, I'd be happy to help you create the tests.
